name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1        
      with:
        node-version: '10.x'
    - name: npm install 
      run: npm install
    - name: lint
      run: npm run lint
    - name: build
      run: npm run build
    - name: test
      run: npm run test
    - name: e2e test
      uses: cypress-io/github-action@v2
      env:
        TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
      with:
        command: npm run test:e2e
        start: npm run start:test
        wait-on: http://localhost:8000
    - uses: akhileshns/heroku-deploy@v3.7.8
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }} 
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "cicd-notes"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        healthcheck: "https://cicd-notes.herokuapp.com/health"
        checkstring: "ok"
        rollbackonhealthcheckfailed: true
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
      if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "main"